#!/usr/bin/env python3
"""
Initialize Graphify for Hermes Cortex.

Run this once after wiki has content:
  python3 scripts/init_graphify.py

Prerequisites:
  uv tool install graphifyy
  graphify install
"""

import os
import subprocess
import sys
from pathlib import Path

_SCRIPTS_DIR = str(Path(__file__).resolve().parent)
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)

from secure_perms import secure_secrets_dir  # noqa: E402

HERMES_HOME_STR = os.environ.get("HERMES_HOME", str(Path.home() / ".hermes"))
HERMES_HOME = Path(HERMES_HOME_STR)
ACTIVE_WIKI = HERMES_HOME / "active-wiki"
ORACLE_BRAIN = HERMES_HOME / "oracle" / "brain"
MAIN_GRAPH_OUT = HERMES_HOME / "graphify-main-out"
ORACLE_GRAPH_OUT = HERMES_HOME / "graphify-oracle-out"
CONFIG_FILE = HERMES_HOME / "graphify-config.env"

def ensure_directories():
    """Create all required directory structure. Cross-platform."""
    dirs = [
        ACTIVE_WIKI / "projects",
        ACTIVE_WIKI / ".meta",
        ORACLE_BRAIN.parent,  # oracle/
        ORACLE_BRAIN,
        HERMES_HOME / "oracle" / "raw" / "research",
        HERMES_HOME / "oracle" / "raw" / "documents",
        HERMES_HOME / "oracle" / "raw" / "articles",
        HERMES_HOME / "oracle" / "raw" / "transcripts",
        HERMES_HOME / "oracle" / "raw" / "conversations",
        HERMES_HOME / "oracle" / "raw" / "imports",
        HERMES_HOME / "oracle" / "raw" / "assets",
        HERMES_HOME / "backups",
        HERMES_HOME / "secrets",
        MAIN_GRAPH_OUT.parent,
        ORACLE_GRAPH_OUT.parent,
    ]
    created = []
    for d in dirs:
        if not d.exists():
            d.mkdir(parents=True, exist_ok=True)
            created.append(str(d))
    return created

def set_secrets_permissions():
    """
    Set 700 permissions on the secrets directory if it exists.

    This referenced an undefined name PERSONAL_AGENT, so it raised NameError on
    every invocation -- and because it was the last step in main(), the script
    always exited non-zero after completing its actual work. A caller checking
    the exit code saw a failed initialization.
    """
    secrets_dir = HERMES_HOME / "secrets"
    if secrets_dir.exists():
        print(f"  [permissions] secrets directory: "
              f"{secure_secrets_dir(secrets_dir)}")

def check_graphify() -> bool:
    """
    Check whether the graphify CLI is available, and report its version.

    graphify ships as the `graphifyy` PyPI package and is deliberately NOT pinned
    to a version anywhere in this repository. Pinning it meant the repo's
    `skills/graphify/.graphify_version` drifted far behind the installed CLI --
    it recorded 0.9.46 while 0.9.67 was current -- and nothing read that file
    anyway. A stale skill is a real problem: graphify ships its own skill copy,
    warns loudly on version skew, and carries platform-specific instructions that
    go out of date. Tracking latest is correct here; the check below reports the
    installed version so a mismatch is visible rather than silent.
    """
    cmd = ["which", "graphify"] if os.name != "nt" else ["where", "graphify"]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True)
    except Exception as e:
        print(f"Error checking graphify: {e}")
        return False

    if result.returncode != 0:
        print("graphify CLI not found. Install the current release with:")
        print("  uv tool install graphifyy        # or: uv tool upgrade graphifyy")
        print("  graphify install --platform hermes   # refresh the bundled skill")
        return False

    ver = subprocess.run(["graphify", "--version"], capture_output=True, text=True)
    # The first line can be a version-skew warning; take the last version-looking token.
    for line in (ver.stdout or "").splitlines():
        if "graphify" in line.lower() and any(c.isdigit() for c in line):
            print(f"  [graphify] {line.strip()}")
            if "warning:" in line.lower() or "skill at" in line.lower():
                print("  [action] run: graphify install --platform hermes")
            break
    return True

def init_config():
    """Create graphify config file."""
    config = f"""# Graphify Configuration for Hermes Cortex
# Generated by init_graphify.py

GRAPHIFY_MAIN_GRAPH={MAIN_GRAPH_OUT}
GRAPHIFY_ORACLE_GRAPH={ORACLE_GRAPH_OUT}
GRAPHIFY_MAIN_SOURCE={ACTIVE_WIKI}
GRAPHIFY_ORACLE_SOURCE={ORACLE_BRAIN}

# Extraction settings
GRAPHIFY_RECURSIVE=true
GRAPHIFY_FOLLOW_LINKS=true
GRAPHIFY_MIN_NODE_LENGTH=3

# Update settings
GRAPHIFY_INCREMENTAL=true
GRAPHIFY_TRACK_CHANGES=true
"""
    os.makedirs(os.path.dirname(CONFIG_FILE), exist_ok=True)
    with open(CONFIG_FILE, "w", encoding="utf-8") as f:
        f.write(config)
    print(f"[OK] Config written to: {CONFIG_FILE}")

def init_graphs():
    """Run initial extraction for both graphs."""
    os.makedirs(MAIN_GRAPH_OUT, exist_ok=True)
    os.makedirs(ORACLE_GRAPH_OUT, exist_ok=True)
    
    # Check if wikis have content
    if os.path.isdir(ACTIVE_WIKI) and os.listdir(ACTIVE_WIKI):
        print(f"\nExtracting Main Graph from {ACTIVE_WIKI}...")
        result = subprocess.run(
            ["graphify", "extract", ACTIVE_WIKI, "--output", MAIN_GRAPH_OUT],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            print(f"  [OK] Main Graph extracted to: {MAIN_GRAPH_OUT}")
        else:
            print(f"  [WARN] Extraction returned code {result.returncode}")
            if result.stderr:
                print(f"  {result.stderr[:200]}")
    else:
        print(f"\nActive Wiki is empty. Skipping Main Graph extraction.")
    
    if os.path.isdir(ORACLE_BRAIN) and os.listdir(ORACLE_BRAIN):
        print(f"\nExtracting Oracle Graph from {ORACLE_BRAIN}...")
        result = subprocess.run(
            ["graphify", "extract", ORACLE_BRAIN, "--output", ORACLE_GRAPH_OUT],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            print(f"  [OK] Oracle Graph extracted to: {ORACLE_GRAPH_OUT}")
        else:
            print(f"  [WARN] Extraction returned code {result.returncode}")
            if result.stderr:
                print(f"  {result.stderr[:200]}")
    else:
        print(f"\nOracle Brain is empty. Skipping Oracle Graph extraction.")

def verify():
    """Verify graphs were created."""
    print("\nVerification:")
    for name, path in [("Main Graph", MAIN_GRAPH_OUT), ("Oracle Graph", ORACLE_GRAPH_OUT)]:
        if os.path.isdir(path) and os.listdir(path):
            print(f"  [OK] {name}: {path}")
        else:
            print(f"  [--] {name}: empty or not yet generated")

def main():
    print("=== Graphify Initialization ===\n")
    
    graphify_available = check_graphify()
    
    if not graphify_available:
        print("Skipping graph extraction (graphify CLI not installed). Config will still be written.")
    
    init_config()
    
    if graphify_available:
        init_graphs()
    else:
        print("[skip] init_graphs() — graphify CLI not installed")
    
    verify()
    set_secrets_permissions()
    
    print("\nNext steps:")
    print("  1. Ingest wiki content")
    print("  2. Run a SEMANTIC extract (update alone is AST-only and yields no")
    print("     semantic relationships over Markdown):")
    print("       graphify extract ~/.hermes/active-wiki \\")
    print("         --backend openai --max-concurrency 1")
    print("     Requires OPENAI_BASE_URL and OPENAI_MODEL for an")
    print("     OpenAI-compatible endpoint. See docs/references/graphify-refresh-pitfall.md")
    print("  3. Verify: python3 scripts/graphify_health.py")
    return 0

if __name__ == "__main__":
    sys.exit(main())
